# ==============================================================================
# BT Navigator Configuration
# DIFFERENCE FROM STANDARD:
# 1. Root node scoped under 'our_bot/bt_navigator'.
# 2. robot_base_frame set to 'our_bot/base_footprint'.
# 3. odom_topic explicitly set to '/our_bot/odom'.
# ==============================================================================
our_bot/bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: our_bot/base_link # Prefixed robot footprint
    odom_topic: /our_bot/odom                # Namespaced odometry topic
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
      search_window: 5.0
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
      search_window: 5.0
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code